function AjaxData(a){this.ajaxExtjs=void 0!=a?a:!0;this.userNo=this.userName="";this.userId=0;this.action=this.paras="";this.success=this.permit=!1;this.value="";this.dataList=[];this.dataList2=[];this.codeTable={codeType:"",dataId:0,display:0,showValues:"",matchValues:"",referValues:"",remark:""}}
AjaxData.prototype.loadUserInfo=function(){var a=this;!0==this.ajaxExtjs?Ext.Ajax.request({url:"../loginmgmt/findCurrentUserInfo.action",success:function(b){b=Ext.JSON.decode(b.responseText);a.userId=b.userId;a.userName=b.userName;a.userNo=b.userNo}}):$.ajax({url:"../loginmgmt/findCurrentUserInfo.action",type:"get",cache:!1,async:!1,dataType:"text",error:function(){alert("Error loading loginmgmt/findCurrentUserInfo")},success:function(b){eval("var resp="+b);a.userId=resp.userId;a.userName=resp.userName;
a.userNo=resp.userNo}});return a};AjaxData.prototype.paraEncode=function(a){var b=this;a="../loginmgmt/paraEncode.action?paras="+a;!0==this.ajaxExtjs?Ext.Ajax.request({url:a,success:function(c){c=Ext.JSON.decode(c.responseText);b.paras=c.paraCode}}):$.ajax({url:a,type:"get",cache:!1,async:!1,dataType:"text",error:function(){alert("Error loading loginmgmt/paraEncode")},success:function(c){eval("var resp="+c);b.paras=resp.paraCode}});return b.paras};
AjaxData.prototype.paraDecode=function(a){var b=this;a="../loginmgmt/paraDecode.action?paras="+a;!0==this.ajaxExtjs?Ext.Ajax.request({url:a,success:function(c){c=Ext.JSON.decode(c.responseText);b.paras=c.paraValue}}):$.ajax({url:a,type:"get",cache:!1,async:!1,dataType:"text",error:function(){alert("Error loading loginmgmt/paraDecode.action")},success:function(c){eval("var resp="+c);b.paras=resp.paraValue}});return b.paras};
AjaxData.prototype.getUserEncodeStr=function(a){var b=this;a="../loginmgmt/userEncodeStr.action?paras="+a;!0==this.ajaxExtjs?Ext.Ajax.request({url:a,success:function(c){c=Ext.JSON.decode(c.responseText);b.paras=c.paraValue}}):$.ajax({url:a,type:"get",cache:!1,async:!1,dataType:"text",error:function(){alert("Error loading loginmgmt/userEncodeStr.action")},success:function(c){eval("var resp="+c);b.paras=resp.paraValue}});return b.paras};
AjaxData.prototype.isPermit=function(a){var b=this;a="../loginmgmt/checkPermit.action?action="+a;!0==this.ajaxExtjs?Ext.Ajax.request({url:a,success:function(c){c=Ext.JSON.decode(c.responseText);b.userId=c.userId;b.action=c.action;b.permit=c.permit}}):$.ajax({url:a,type:"get",cache:!1,async:!1,dataType:"text",error:function(){alert("Error loading loginmgmt/checkPermit.action")},success:function(c){eval("var resp="+c);b.userId=resp.userId;b.action=resp.action;b.permit=resp.permit}});return b.permit};
AjaxData.prototype.getSysconfigValue=function(a){var b=this;a="../basedata/findSysconfigValue.action?sysconfigCode="+a;!0==this.ajaxExtjs?Ext.Ajax.request({url:a,success:function(c){c=Ext.JSON.decode(c.responseText);b.value=c.sysconfigValue}}):$.ajax({url:a,type:"get",cache:!1,async:!1,dataType:"text",error:function(){alert("Error loading basedata/findSysconfigValue.action")},success:function(c){eval("var resp="+c);b.value=resp.sysconfigValue}});return b.value};
AjaxData.prototype.getCodeTableByDataId=function(a,b){var c=this,d="../basedata/findCodeTableByDataId.action?codeType="+a+"&dataId="+b;!0==this.ajaxExtjs?Ext.Ajax.request({url:d,success:function(a){a=Ext.JSON.decode(a.responseText);c.codeTable=a}}):$.ajax({url:d,type:"get",cache:!1,async:!1,dataType:"text",error:function(){alert("Error loading basedata/findCodeTableByDataId.action")},success:function(a){eval("var resp="+a);c.codeTable=resp}});return c.value};
AjaxData.prototype.getUserParameterValue=function(a){var b=this;a="../basedata/findUserParameterByCode.action?parameterCode="+a;!0==this.ajaxExtjs?Ext.Ajax.request({url:a,success:function(a){a=Ext.JSON.decode(a.responseText);b.value=a.value;b.userId=a.userId}}):$.ajax({url:a,type:"get",cache:!1,async:!1,dataType:"text",error:function(){alert("Error loading basedata/findUserParameterByCode.action")},success:function(a){eval("var resp="+a);b.userId=resp.userId;b.value=resp.value}});return b.value};
AjaxData.prototype.saveUserParameterValue=function(a,b){var c=this,d="../basedata/saveUserParameterByCode.action?parameterCode="+a+"&parameterValue="+b;!0==this.ajaxExtjs?Ext.Ajax.request({url:d,success:function(a){a=Ext.JSON.decode(a.responseText);c.success=a.success}}):$.ajax({url:d,type:"post",cache:!1,async:!1,dataType:"text",error:function(){alert("Error save basedata/saveUserParameterByCode.action")},success:function(a){eval("var resp="+a);c.success=resp.success;!0==resp.success?alert("\u4fdd\u5b58\u6210\u529f"):
alert(resp.status)}});return c.success};
AjaxData.prototype.saveRecentlyInput=function(a,b,c){var d=this;a="../basedata/saveInput.action?module_id="+a+"&prop_name="+b+"&input="+c;!0==this.ajaxExtjs?Ext.Ajax.request({url:a,success:function(a){a=Ext.JSON.decode(a.responseText);d.success=a.success}}):$.ajax({url:a,type:"post",cache:!1,async:!0,dataType:"text",error:function(){alert("Error save basedata/saveInput.action")},success:function(a){eval("var resp="+a);d.success=resp.success;!0==resp.success?alert("\u4fdd\u5b58\u6210\u529f"):alert(resp.status)}});
return d.success};
AjaxData.prototype.clearModuleCache=function(a){var b=this;a="../loginmgmt/clearModuleCache.action?mmKey="+a;!0==this.ajaxExtjs?Ext.Ajax.request({url:a,success:function(a){a=Ext.JSON.decode(a.responseText);b.success=a.success;b.success&&alert(a.paras)}}):$.ajax({url:a,type:"get",cache:!1,async:!1,dataType:"text",error:function(){alert("Error loading loginmgmt/clearModuleCache.action")},success:function(a){eval("var resp="+a);b.success=resp.success;b.success&&alert(resp.paras)}});return b.success};
AjaxData.prototype.getTableOptByModuleId=function(a){var b=this;a="../basedata/findTableOptByModuleId.action?moduleId="+a;!0==this.ajaxExtjs?Ext.Ajax.request({url:a,success:function(a){a=Ext.JSON.decode(a.responseText);b.dataList=a}}):$.ajax({url:a,type:"get",cache:!1,async:!1,dataType:"text",error:function(){alert("Error loading basedata/findTableOptByModuleId.action")},success:function(a){eval("var resp="+a);b.dataList=resp}});return b.dataList};
AjaxData.prototype.getTableOptDataByModuleId=function(a,b){var c=this,d="../basedata/findTableOptDataByModuleId.action?moduleId="+a+"&dataIds="+b;!0==this.ajaxExtjs?Ext.Ajax.request({url:d,success:function(a){a=Ext.JSON.decode(a.responseText);c.dataList2=a}}):$.ajax({url:d,type:"get",cache:!1,async:!1,dataType:"text",error:function(){alert("Error loading basedata/findTableOptDataByModuleId.action")},success:function(a){eval("var resp="+a);c.dataList2=resp}});return c.dataList2};
function getCookie(a){for(var b=document.cookie.split("; "),c=0;c<b.length;c++){var d=b[c].split("=");if(d[0]==a)return d[1]}return""};
