var lang=getCookie("locale"),LANG_CN="zh_CN",LANG_EN="en_US";function getDictValue(b){var d;"string"==typeof b&&(d=b.indexOf("</"),0<=d&&(b=b.substring(0,d)),d=b.indexOf(">"),0<=b.indexOf(">")&&(b=b.substring(d+1)));return b}function getValueColor(b,d){if(!d||""==d)d="black";return"<font color='"+d+"'>"+b+"</font>"}function getDictBoolean(b){for(var d=[],a,c,e=0;e<b.length;e++)a=b[e],c=!1,1==a.id&&(c=!0),a=lang==LANG_EN&&a.valueEn?{id:c,value:a.valueEn}:{id:c,value:a.value},d.push(a);return d}
function getDataArray(b,d){var a=[],c=[];"all"==d&&(c.push(""),lang==LANG_EN?c.push("All"):c.push("\u5168\u90e8"),a.push(c));for(var e,f=0;f<b.length;f++)e=b[f],c=[],c.push(""+e.id),lang==LANG_EN&&e.valueEn?c.push(e.valueEn):c.push(e.value),a.push(c);return a}
function getDataArrayValue(b,d){var a=[],c=[];"all"==d&&(c.push(""),lang==LANG_EN?c.push("All"):c.push("\u5168\u90e8"),a.push(c));for(var e,f=0;f<b.length;f++)e=b[f],c=[],c.push(e.id),lang==LANG_EN&&e.valueEn?c.push(e.valueEn):c.push(e.value),a.push(c);return a}function getDataStore(b,d){return new Ext.data.SimpleStore({fields:["key","value"],data:getDataArray(b,d)})}
function renderIf(b,d){var a,c;for(c in dict_if)if(a=dict_if[c],b==a.id)return!0==d&&a.valueEn?lang==LANG_EN?a.valueEn:a.value:lang==LANG_EN&&a.valueEn?getValueColor(a.valueEn,a.color):getValueColor(a.value,a.color);return b}function renderIfDel(b,d){var a,c;for(c in dict_if_del)if(a=dict_if_del[c],b==a.id)return!0==d&&a.valueEn?lang==LANG_EN?a.valueEn:a.value:lang==LANG_EN&&a.valueEn?getValueColor(a.valueEn,a.color):getValueColor(a.value,a.color);return b}
function renderStatus(b,d){var a,c;for(c in dict_status)if(a=dict_status[c],b==a.id)return!0==d&&a.valueEn?lang==LANG_EN?a.valueEn:a.value:lang==LANG_EN&&a.valueEn?getValueColor(a.valueEn,a.color):getValueColor(a.value,a.color);return b}function renderLogLevel(b,d){var a,c;for(c in dict_log_level)if(a=dict_log_level[c],b==a.id)return!0==d&&a.valueEn?lang==LANG_EN?a.valueEn:a.value:lang==LANG_EN&&a.valueEn?getValueColor(a.valueEn,a.color):getValueColor(a.value,a.color);return b}
function renderOrderType(b,d){var a,c;for(c in dict_order_type)if(a=dict_order_type[c],b==a.id)return!0==d&&a.valueEn?lang==LANG_EN?a.valueEn:a.value:lang==LANG_EN&&a.valueEn?getValueColor(a.valueEn,a.color):getValueColor(a.value,a.color);return b}
function renderRecentlyLimit(b,d){var a,c;for(c in dict_recently_limit)if(a=dict_recently_limit[c],b==a.id)return!0==d&&a.valueEn?lang==LANG_EN?a.valueEn:a.value:lang==LANG_EN&&a.valueEn?getValueColor(a.valueEn,a.color):getValueColor(a.value,a.color);return b}
function renderRecentlyClearType(b,d){var a,c;for(c in dict_recently_clear_type)if(a=dict_recently_clear_type[c],b==a.id)return!0==d&&a.valueEn?lang==LANG_EN?a.valueEn:a.value:lang==LANG_EN&&a.valueEn?getValueColor(a.valueEn,a.color):getValueColor(a.value,a.color);return b}
function renderRecentlyShowType(b,d){var a,c;for(c in dict_recently_show_type)if(a=dict_recently_show_type[c],b==a.id)return!0==d&&a.valueEn?lang==LANG_EN?a.valueEn:a.value:lang==LANG_EN&&a.valueEn?getValueColor(a.valueEn,a.color):getValueColor(a.value,a.color);return b}function renderSex(b,d){var a,c;for(c in dict_sex)if(a=dict_sex[c],b==a.id)return!0==d&&a.valueEn?lang==LANG_EN?a.valueEn:a.value:lang==LANG_EN&&a.valueEn?getValueColor(a.valueEn,a.color):getValueColor(a.value,a.color);return b}
function renderIfBoolean(b){for(var d in dict_if)return b?lang==LANG_EN?getValueColor("Yes"):getValueColor("\u662f"):lang==LANG_EN?getValueColor("No","red"):getValueColor("\u5426","red");return b}function getCookie(b){for(var d=document.cookie.split("; "),a=0;a<d.length;a++){var c=d[a].split("=");if(c[0]==b)return c[1]}return""};
